"""Pre-migration for l10n_ve_donation: v17 -> v19.

stock.scrap.donation_reason (free-text Char) does not exist in v19.
It wasn't dropped for no reason: v19 redesigned donation reasons as
tags (stock.scrap.scrap_reason_tag_ids, core Odoo 19's
stock.scrap.reason.tag model), reusing the standard scrap-reason-tag
feature instead of a bespoke text field. Free text can't be perfectly
folded into tags automatically (typos, inconsistent wording would
create near-duplicate tags), but leaving it as dead backup-only data
loses real usability. This backs up the raw text either way, then
best-efforts a tag migration: one stock.scrap.reason.tag per distinct
non-empty donation_reason value, linked to the scraps that had it.

Also backs up res_company.account_stock_journal_id as a safety copy.
That column is not gone in v19: it is the core stock_account field
(stock_account/models/res_company.py), which l10n_ve_donation reads in
stock_move.py and declares as a direct dependency in its manifest. The
column itself is kept as is -- see MIGRATION_NOTES_donation.md in this
folder.
"""

import logging

_logger = logging.getLogger(__name__)

BACKUP_TABLE = "l10n_ve_donation_migration_v17_backup"


def _column_exists(cr, table, column):
    cr.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = %s AND column_name = %s",
        (table, column),
    )
    return bool(cr.fetchone())


def _ensure_backup_table(cr):
    cr.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {BACKUP_TABLE} (
            id SERIAL PRIMARY KEY,
            source_table VARCHAR NOT NULL,
            source_column VARCHAR NOT NULL,
            record_id INTEGER NOT NULL,
            value_text TEXT,
            backed_up_at TIMESTAMP DEFAULT now()
        )
        """
    )


def _backup_simple_column(cr, table, column):
    if not _column_exists(cr, table, column):
        _logger.info("  %s.%s does not exist, nothing to back up", table, column)
        return

    cr.execute(
        f'SELECT id, "{column}" FROM "{table}" WHERE "{column}" IS NOT NULL'  # noqa: S608
    )
    rows = cr.fetchall()
    if not rows:
        _logger.info("  %s.%s has no non-null values, nothing to back up", table, column)
        return

    cr.executemany(
        f"""
        INSERT INTO {BACKUP_TABLE} (source_table, source_column, record_id, value_text)
        VALUES (%s, %s, %s, %s)
        """,
        [(table, column, rec_id, str(value)) for rec_id, value in rows],
    )
    _logger.info("  Backed up %s row(s) from %s.%s", len(rows), table, column)


def _find_scrap_tag_rel_table(cr):
    """The m2m relation table name for stock.scrap.scrap_reason_tag_ids
    is auto-generated by Odoo (confirmed: stock_scrap_stock_scrap_reason_tag_rel,
    columns stock_scrap_id/stock_scrap_reason_tag_id) -- looked up instead
    of hardcoding it, in case naming ever changes across versions.
    ORDER BY + LIMIT 1 (2nd-pass audit fix, N-15): fetchone() without an
    explicit order was non-deterministic if the LIKE pattern ever matched
    more than one table -- pin it to the shortest/first alphabetical match
    instead of whatever order Postgres happened to return.
    """
    cr.execute(
        """
        SELECT table_name FROM information_schema.tables
        WHERE table_name LIKE 'stock_scrap%reason_tag%'
          AND table_name != 'stock_scrap_reason_tag'
        ORDER BY table_name
        LIMIT 1
        """
    )
    row = cr.fetchone()
    return row[0] if row else None


def _migrate_donation_reason_to_tags(cr):
    if not _column_exists(cr, "stock_scrap", "donation_reason"):
        _logger.info("  stock_scrap.donation_reason does not exist, nothing to migrate")
        return
    if not _column_exists(cr, "stock_scrap_reason_tag", "name"):
        _logger.info(
            "  stock_scrap_reason_tag table not found (stock module scrap-reason-tags "
            "not installed) -- skipping tag migration, text values stay in the backup "
            "table only"
        )
        return

    rel_table = _find_scrap_tag_rel_table(cr)
    if not rel_table:
        _logger.warning(
            "  Could not find the stock.scrap <-> stock.scrap.reason.tag relation "
            "table -- skipping tag migration, text values stay in the backup table only"
        )
        return

    cr.execute(
        "SELECT data_type FROM information_schema.columns "
        "WHERE table_name = 'stock_scrap_reason_tag' AND column_name = 'name'"
    )
    (name_data_type,) = cr.fetchone()
    is_translated_json = name_data_type in ("json", "jsonb")

    cr.execute(
        "SELECT id, donation_reason FROM stock_scrap "
        "WHERE donation_reason IS NOT NULL AND btrim(donation_reason) != ''"
    )
    scraps = cr.fetchall()
    if not scraps:
        _logger.info("  No stock.scrap has a non-empty donation_reason, nothing to migrate")
        return

    # BUG FIXED (found by independent audit, verified against Odoo 19 core):
    # stock.scrap.reason.tag.name is `fields.Char(..., translate=True)`, which
    # modern Odoo stores as JSONB (e.g. {"en_US": "text"}), NOT plain text.
    # `WHERE name = ANY(%s)` with a text[] against a jsonb column raises
    # "operator does not exist: jsonb = text" and aborts this whole migration
    # transaction the first time any donation_reason is non-empty -- this
    # isn't a data-quality issue, it's a hard failure blocking the upgrade.
    # Fix: compare/insert against the 'en_US' key explicitly, matching how
    # Odoo itself stores the untranslated/source value of a translatable field.
    #
    # One tag per distinct trimmed text value (case-sensitive on purpose --
    # collapsing case/typo variants is a judgment call left to whoever
    # cleans up the tag list afterward, not something to guess silently).
    distinct_reasons = sorted({text.strip() for _id, text in scraps})
    if is_translated_json:
        select_sql = "SELECT name->>'en_US', id FROM stock_scrap_reason_tag WHERE name->>'en_US' = ANY(%s)"
        insert_sql = (
            "INSERT INTO stock_scrap_reason_tag (name, sequence, color) "
            "VALUES (jsonb_build_object('en_US', %s), 10, '#3C3C3C')"
        )
    else:
        select_sql = "SELECT name, id FROM stock_scrap_reason_tag WHERE name = ANY(%s)"
        insert_sql = (
            "INSERT INTO stock_scrap_reason_tag (name, sequence, color) "
            "VALUES (%s, 10, '#3C3C3C')"
        )

    cr.execute(select_sql, (distinct_reasons,))
    existing_tags = dict(cr.fetchall())

    new_reasons = [r for r in distinct_reasons if r not in existing_tags]
    if new_reasons:
        cr.executemany(insert_sql, [(r,) for r in new_reasons])
        cr.execute(select_sql, (distinct_reasons,))
        existing_tags = dict(cr.fetchall())

    links = [
        (scrap_id, existing_tags[text.strip()])
        for scrap_id, text in scraps
        if text.strip() in existing_tags
    ]
    if links:
        cr.executemany(
            f'INSERT INTO "{rel_table}" (stock_scrap_id, stock_scrap_reason_tag_id) '  # noqa: S608
            f"VALUES (%s, %s) ON CONFLICT DO NOTHING",
            links,
        )
    _logger.info(
        "  Migrated donation_reason to tags: %s distinct tag(s) created/matched, "
        "%s scrap(s) linked",
        len(distinct_reasons), len(links),
    )


def migrate(cr, version):
    _logger.info("l10n_ve_donation pre-migrate: backing up and tag-migrating donation fields")
    _ensure_backup_table(cr)
    _backup_simple_column(cr, "stock_scrap", "donation_reason")
    _backup_simple_column(cr, "res_company", "account_stock_journal_id")
    _migrate_donation_reason_to_tags(cr)
    _logger.info(
        "l10n_ve_donation pre-migrate: res_company.account_stock_journal_id backed up "
        "as a safety copy; it is the core stock_account field and stays in place. "
        "See MIGRATION_NOTES_donation.md."
    )
